adapters:
  mongo: sails-mongo

connections:
  db:
    adapter: mongo
    host: localhost
    port: 27017
    database: blog
    schema: true

models:
  - ./post

resource:
#  controller: post
  path: /post
